<?php
/**
 * ACF fields for the project post type
 *
 * @package    KW_Prod
 * @subpackage Fields
 * @category   ACF
 * @since      1.0.0
 */

 namespace KWProd\Fields\Project;

 // Restrict direct access.
 if ( ! defined( 'ABSPATH' ) ) {
	 die;
 }

/**
 * Execute functions
 *
 * @since  1.0.0
 * @return void
 */
function setup() {

	// Return namespaced function.
	$ns = function( $function ) {
		return __NAMESPACE__ . "\\$function";
	};

	add_action( 'acf/init', $ns( 'fields' ) );
}

/**
 * ACF field group
 *
 * @since  1.0.0
 * @return void
 */
function fields() {

	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( [
		'key'    => 'group_5948b2c4ec0dd-2',
		'title'  => __( 'Projects', 'kw-prod-design' ),
		'fields' => [
			[
				'key'               => 'field_5982561e5eb94',
				'label'             => __( 'Info', 'kw-prod-design' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement' => 'top',
				'endpoint'  => 0,
			],
			[
				'key'               => 'field_5dceeb578c44c',
				'label'             => __( 'Project Title', 'kw-prod-design' ),
				'name'              => 'project_title',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => __( 'This optional title can be used to override the administrative title above.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_field_group_condition' => 0,
				'default_value' => '',
				'maxlength'     => '',
				'placeholder'   => __( '', 'kw-prod-design' ),
				'prepend'       => '',
				'append'        => '',
			],
			[
				'key'               => 'field_61e5a8b26cb98',
				'label'             => __( 'Project Types', 'kw-prod-design' ),
				'name'              => 'project_types',
				'aria-label'        => '',
				'type'              => 'acfe_taxonomy_terms',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'taxonomy' => [
					0 => 'project_type',
				],
				'allow_terms' => '',
				'allow_level' => '',
				'field_type'  => 'checkbox',
				'min' => '',
				'max' => '',
				'default_value' => [],
				'return_format' => 'id',
				'layout'        => 'horizontal',
				'toggle'        => 0,
				'save_terms'    => 1,
				'load_terms'    => 0,
				'acfe_field_group_condition' => 0,
				'choices'            => [],
				'ui'                 => 0,
				'multiple'           => 0,
				'allow_null'         => 0,
				'ajax'               => 0,
				'placeholder'        => __( '', 'kw-prod-design' ),
				'search_placeholder' => __( '', 'kw-prod-design' ),
				'allow_custom'       => 0,
				'other_choice'       => 0,
			],
			[
				'key'               => 'field_61e8b0e104a98',
				'label'             => __( 'Project Roles', 'kw-prod-design' ),
				'name'              => 'project_roles',
				'aria-label'        => '',
				'type'              => 'acfe_taxonomy_terms',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'taxonomy' => [
					0 => 'project_role',
				],
				'allow_terms' => '',
				'allow_level' => '',
				'field_type'  => 'checkbox',
				'min' => '',
				'max' => '',
				'default_value' => [],
				'return_format' => 'id',
				'layout'        => 'horizontal',
				'toggle'        => 0,
				'save_terms'    => 1,
				'load_terms'    => 0,
				'acfe_field_group_condition' => 0,
				'choices'            => [],
				'ui'                 => 0,
				'multiple'           => 0,
				'allow_null'         => 0,
				'ajax'               => 0,
				'placeholder'        => __( '', 'kw-prod-design' ),
				'search_placeholder' => __( '', 'kw-prod-design' ),
				'allow_custom'       => 0,
				'other_choice'       => 0,
			],
			[
				'key'               => 'field_5e483aa1319e0',
				'label'             => __( 'Client', 'kw-prod-design' ),
				'name'              => 'project_client',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => __( 'Name(s) of the production company or network.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_permissions' => '',
				'default_value'    => '',
				'placeholder'      => __( '', 'kw-prod-design' ),
				'prepend'          => '',
				'append'           => '',
				'maxlength'        => '',
			],
			[
				'key'               => 'field_5948b2c4f2275',
				'label'             => __( 'Director', 'kw-prod-design' ),
				'name'              => 'project_director',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => __( 'Enter only the name of the director, if applicable.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value' => '',
				'placeholder'   => __( '', 'kw-prod-design' ),
				'prepend'       => '',
				'append'        => '',
				'maxlength'     => '',
			],
			[
				'key'               => 'field_5948b4fe4177e',
				'label'             => __( 'IMDb Page', 'kw-prod-design' ),
				'name'              => 'project_imdb_page',
				'aria-label'        => '',
				'type'              => 'url',
				'instructions'      => __( 'Paste the URL (web address) of the main page on IMBd.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value' => '',
				'placeholder'   => __( 'http://www.imdb.com/title/tt1234567/', 'kw-prod-design' ),
			],
			[
				'key'               => 'field_5948b699882a3',
				'label'             => __( 'Description', 'kw-prod-design' ),
				'name'              => 'project_description',
				'aria-label'        => '',
				'type'              => 'textarea',
				'instructions'      => __( 'Enter a brief description. Paragraphs automatically added with breaks between lines.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value' => '',
				'placeholder'   => __( '', 'kw-prod-design' ),
				'maxlength'     => '',
				'rows'          => '',
				'new_lines'     => 'wpautop',
			],
			[
				'key'               => 'field_5e483d21d0ca2',
				'label'             => __( 'Images', 'kw-prod-design' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_permissions' => '',
				'placement'        => 'top',
				'endpoint'         => 0,
				'icon_class'       => '',
				'show_icon_only'   => 0,
			],
			[
				'key'               => 'field_5ddc4e64349e8',
				'label'             => __( 'Poster Image', 'kw-prod-design' ),
				'name'              => 'project_poster_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => __( 'The poster image uses a 2:3 aspect ratio, taller than wide. The minimum size is 426 pixels wide by 640 pixels high. Ideal is 853 x 1280 or greater.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_field_group_condition' => 0,
				'uploader'       => '',
				'acfe_thumbnail' => 0,
				'return_format'  => 'array',
				'min_width'      => '',
				'min_height'     => '',
				'min_size'       => '',
				'max_width'      => '',
				'max_height'     => '',
				'max_size'       => '',
				'mime_types'     => 'jpg, jpeg, png',
				'preview_size'   => 'thumbnail-poster',
				'library'        => 'all',
			],
			[
				'key'               => 'field_61e5a21cb8ccf',
				'label'             => __( 'Screenshot Image', 'kw-prod-design' ),
				'name'              => 'project_screenshot_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => __( 'The screenshot image uses a 16:9 HD video aspect ratio. The minimum size is 1280 pixels wide by 720 pixels high.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_field_group_condition' => 0,
				'uploader'       => '',
				'acfe_thumbnail' => 0,
				'return_format'  => 'array',
				'min_width'      => '',
				'min_height'     => '',
				'min_size'       => '',
				'max_width'      => '',
				'max_height'     => '',
				'max_size'       => '',
				'mime_types'     => 'jpg, jpeg, png',
				'preview_size'   => 'thumbnail-video',
				'library'        => 'all',
			],
			[
				'key'               => 'field_5e483d3195947',
				'label'             => __( 'Image Gallery', 'kw-prod-design' ),
				'name'              => 'project_gallery',
				'aria-label'        => '',
				'type'              => 'gallery',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_permissions' => '',
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'insert'        => 'append',
				'library'       => 'all',
				'min'           => '',
				'max'           => '',
				'min_width'     => '',
				'min_height'    => '',
				'min_size'      => '',
				'max_width'     => '',
				'max_height'    => '',
				'max_size'      => '',
				'mime_types'    => '',
			],
			[
				'key'               => 'field_598256325eb95',
				'label'             => __( 'Videos', 'kw-prod-design' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'tab',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement' => 'top',
				'endpoint'  => 0,
			],
			[
				'key'               => 'field_5e482f96e5494',
				'label'             => __( 'Video Requirements', 'kw-prod-design' ),
				'name'              => '',
				'aria-label'        => '',
				'type'              => 'message',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_permissions' => '',
				'message'          => __( 'Video field are designed to work only with videos hosted on Vimeo. Use only the basic URL of the video, no full-screen URLs or embed code.', 'kw-prod-design' ),
				'new_lines'        => 'wpautop',
				'esc_html'         => 0,
			],
			[
				'key'               => 'field_5e48368887fa8',
				'label'             => __( 'Primary Video Title', 'kw-prod-design' ),
				'name'              => 'project_video_title',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_permissions' => '',
				'default_value'    => '',
				'placeholder'      => __( '', 'kw-prod-design' ),
				'prepend'          => '',
				'append'           => '',
				'maxlength'        => '',
			],
			[
				'key'               => 'field_5948b2c4f2479',
				'label'             => __( 'Primary Video URL', 'kw-prod-design' ),
				'name'              => 'project_vimeo_url',
				'aria-label'        => '',
				'type'              => 'url',
				'instructions'      => __( 'Enter the basic URL for the Vimeo video.', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value' => '',
				'placeholder'   => __( 'https://vimeo.com/123456789', 'kw-prod-design' ),
			],
			[
				'key'               => 'field_5e4829feeae2a',
				'label'             => __( 'Additional Videos', 'kw-prod-design' ),
				'name'              => 'project_additional_videos',
				'aria-label'        => '',
				'type'              => 'repeater',
				'instructions'      => __( '', 'kw-prod-design' ),
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_5948b2c4f2479',
							'operator' => '!=empty',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'acfe_permissions'              => '',
				'acfe_repeater_stylised_button' => 0,
				'collapsed'     => 'field_5e482a1beae2b',
				'min'           => 0,
				'max'           => 0,
				'layout'        => 'row',
				'button_label'  => __( 'Add Video', 'kw-prod-design' ),
				'rows_per_page' => 20,
				'sub_fields'    => [
					[
						'key'               => 'field_5e482a1beae2b',
						'label'             => __( 'Title', 'kw-prod-design' ),
						'name'              => 'project_additional_video_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => __( '', 'kw-prod-design' ),
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'acfe_permissions' => '',
						'default_value'    => '',
						'placeholder'      => __( '', 'kw-prod-design' ),
						'prepend'          => '',
						'append'           => '',
						'maxlength'        => '',
						'parent_repeater'  => 'field_5e4829feeae2a',
					],
					[
						'key'               => 'field_5e482a37eae2c',
						'label'             => __( 'URL', 'kw-prod-design' ),
						'name'              => 'project_additional_vimeo_url',
						'aria-label'        => '',
						'type'              => 'url',
						'instructions'      => __( '', 'kw-prod-design' ),
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => '',
							'class' => '',
							'id'    => '',
						],
						'default_value'   => '',
						'placeholder'     => __( 'https://vimeo.com/123456789', 'kw-prod-design' ),
						'acfe_field_group_condition' => 0,
						'parent_repeater' => 'field_5e4829feeae2a',
					],
				],
			],
		],
		'location' => [
			[
				[
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'project',
				],
			],
		],
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => [
			0  => 'author',
			1  => 'categories',
			2  => 'comments',
			3  => 'the_content',
			4  => 'discussion',
			5  => 'excerpt',
			6  => 'format',
			7  => 'page_attributes',
			8  => 'revisions',
			9  => 'send-trackbacks',
			10 => 'slug',
			11 => 'tags',
		],
		'active'        => true,
		'description'   => __( 'For Projects post types.', 'kw-prod-design' ),
		'show_in_rest'  => 0,
		'acfe_autosync' => [
			0 => 'php',
			1 => 'json',
		],
		'acfe_form' => 0,
		'acfe_display_title' => '',
		'acfe_meta' => '',
		'acfe_note' => '',
	] );
}
